version: '3.7'
services:
    postgrs:
        image: postgres
        restart: always
        environment: 
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=TEST
          - PGDATA=tmp
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5434:5432'
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./postgresql/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
